const SESSIONTYPE_WEB = 1;

const MESSAGEDIRECTION_OUT = 1;
const MESSAGEDIRECTION_IN = 2;

const STARTING_PAGE = 'module_conversations convlist_active';

const ICON_FAVORITE = '/images/FavoriteStar-favorite.svg';
const ICON_NOTFAVORITE = '/images/FavoriteStar-unfavorite.svg';

//Privileges
const EDITACCOUNTS = 1;
const ALLCONVERSATIONS = 2;
const COMPANYTEMPLATE = 3;
const COMPANYSIGNATURE = 4;
const COMPANYTRAFFIC = 5;

const MESSAGESTATUS_CREATED = 0;
const MESSAGESTATUS_SENT = 1;
const MESSAGESTATUS_SENDFAIL = 2;
const MESSAGESTATUS_DELIVERED = 3;
const MESSAGESTATUS_DELIVERYFAILED = 4;
const MESSAGESTATUS_DELIVERYBUFFERED = 5;
const MESSAGESTATUS_DELIVERY_UNKNOWN= 6;
const MESSAGESTATUS_RECEIVED = 7;